name: Unzip db.zip

on:
  workflow_dispatch:  # Allows you to manually trigger the unzip

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Unzip db.zip
        run: unzip db.zip -d db_extracted

      - name: Commit and push unzipped contents
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add db_extracted/
          git commit -m "Extracted db.zip into db_extracted/"
          git push
